CREATE TABLE "tasks" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
    "title" character varying NOT NULL, 
    "description" text NOT NULL, 
    "priority" "priority" NOT NULL, 
    "status" "status" NOT NULL, 
    "started_at" timestamptz NOT NULL, 
    "finished_at" timestamptz NOT NULL, 
    "created_at" timestamptz NOT NULL  DEFAULT now(), 
    "updated_at" timestamptz NOT NULL  DEFAULT now(), 
    PRIMARY KEY ("id")
);
