CREATE TABLE "labels" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
    "name" character varying NOT NULL, 
    "created_at" timestamptz NOT NULL  DEFAULT now(), 
    "updated_at" timestamptz NOT NULL  DEFAULT now(), 
    PRIMARY KEY ("id")
);
